### ISSUE TITLE
Frontend API: do not send OPTIONS

### ISSUE THREAD

**Issue by pruf1** [LearningBay24/LearningBay24-react#20]

**Comment by Witcher01** [comment]
Ist das damit gelöst? @pruf1 

https://github.com/LearningBay24/LearningBay24-backend/commit/9f8dc5a031873450fc52fe6752da4b582d1b990a#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R36-R46
