### ISSUE TITLE
Belegte Kurse werden unter "Meine Kurse" angezeigt

### ISSUE THREAD

**Issue by Witcher01** [LearningBay24/LearningBay24-react#92]

**Comment by Icola1** [comment]
Es gibt nur GetCoursesFromUser selbst im Backend da wird aktuell wohl noch gar nicht unterschieden

**Comment by Witcher01** [comment]
Hm okay... Muss ich mir morgen Gedanken drum machen bzw. dann einfach implementieren, falls ich mich so entscheide

**Comment by Witcher01** [comment]
Blocked-on: https://github.com/LearningBay24/LearningBay24-backend/issues/131

**Comment by Witcher01** [comment]
Funktionalität wurde im Backend implementiert. @Icola1 kannst implementieren
